export interface Assistido {
  nome: string,
  email?: string,
  cpf?: string,
  rg?: string,
  naturalidade?: string,
  nacionalidade?: string,
  dataNascimento?: string,
  estadoCivil?: string,
  telefone?: string,
  cidade?: string,
  cep?: string,
  enderecoResidencial?: string,
  escolaridade?: string,
  nomePai?: string,
  nomeMae?: string,
  profissao?: string,
  remuneracao?: string,
  cidadeComercial?: string,
  enderecoComercial?: string,
  numDependentes?: string,
}
